# Generated by Django 5.1.4 on 2025-01-10 16:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("animals", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="animaltype",
            old_name="icon",
            new_name="digital_icon",
        ),
        migrations.AlterField(
            model_name="rgrequest",
            name="qr_data",
            field=models.BooleanField(default=False),
        ),
    ]
