# Generated by Django 5.1.4 on 2025-01-10 17:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("animals", "0002_rename_icon_animaltype_digital_icon_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="rgrequest",
            old_name="qr_data",
            new_name="qr_code_data",
        ),
        migrations.AddField(
            model_name="rgrequest",
            name="qr_code_image",
            field=models.ImageField(blank=True, null=True, upload_to="qr_codes/"),
        ),
    ]
