# Generated by Django 5.1.4 on 2025-01-10 17:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("animals", "0004_rename_tutor_contact_rgrequest_tutor_phone_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rgrequest",
            name="tutor_address",
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name="rgrequest",
            name="tutor_name",
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name="rgrequest",
            name="tutor_phone",
            field=models.TextField(max_length=100),
        ),
    ]
