# Generated by Django 5.1.4 on 2025-01-10 17:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("animals", "0006_alter_rgrequest_tutor_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="rgrequest",
            name="rg_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
