# Generated by Django 5.1.4 on 2025-01-10 17:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("animals", "0007_rgrequest_rg_url"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="rgrequest",
            name="rg_url",
        ),
    ]
